const fs = require('fs');
const path = require('path');

// 1. Define our sites
const sites = [
  {
    id: "toonily-source",
    name: "Toonily",
    version: "1.0.0",
    lang: "en",
    nsfw: true,
    baseUrl: "https://toonily.com",
    template: "madara.js"
  },
  {
    id: "3asq-source",
    name: "3asq",
    version: "1.0.0",
    lang: "ar",
    nsfw: false,
    baseUrl: "https://3asq.online",
    template: "madara.js"
  }
];

const templatesDir = path.join(__dirname, '../src/templates');
const publicDir = path.join(__dirname, '../public');
const repoJsonPath = path.join(publicDir, 'repo.json');

// Ensure public directory exists
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
}

// 2. Load existing repo.json
let repo = { name: "My Manga Plugins", plugins: [] };
if (fs.existsSync(repoJsonPath)) {
  try {
    repo = JSON.parse(fs.readFileSync(repoJsonPath, 'utf8'));
  } catch (e) {
    console.error("Failed to parse existing repo.json, creating a new one.");
  }
}

// 3. Generate plugins
for (const site of sites) {
  const templatePath = path.join(templatesDir, site.template);
  if (!fs.existsSync(templatePath)) {
    console.error(`Template ${site.template} not found for site ${site.name}`);
    continue;
  }
  
  const templateCode = fs.readFileSync(templatePath, 'utf8');
  
  // Create the final plugin string
  const pluginCode = `
// AUTOGENERATED PLUGIN FOR ${site.name}
// Template: ${site.template}

${templateCode}

// Initialize and register the plugin
const config = ${JSON.stringify(site, null, 2)};
const plugin = new MadaraTemplate(config);
harbor.register(plugin);
`;

  // Write the plugin file
  const pluginFilename = `${site.id}.js`;
  fs.writeFileSync(path.join(publicDir, pluginFilename), pluginCode.trim());
  console.log(`Generated plugin for ${site.name}: ${pluginFilename}`);
  
  // Update repo.json
  const existingIndex = repo.plugins.findIndex(p => p.id === site.id);
  const pluginEntry = {
    id: site.id,
    name: site.name,
    version: site.version,
    lang: site.lang,
    nsfw: site.nsfw,
    icon: site.baseUrl + "/favicon.ico",
    entry: pluginFilename
  };
  
  if (existingIndex >= 0) {
    repo.plugins[existingIndex] = pluginEntry;
  } else {
    repo.plugins.push(pluginEntry);
  }
}

// 4. Save repo.json
fs.writeFileSync(repoJsonPath, JSON.stringify(repo, null, 2));
console.log("Updated repo.json successfully!");
